version: 2.1
executors:
  test-go118:
    docker:
      - image: "cimg/go:1.18"
    environment:
      runrace: true
      TIMESCALE_FACTOR: 3
  test-go119:
    docker:
      - image: "cimg/go:1.19"
    environment:
      runrace: true
      TIMESCALE_FACTOR: 3
  test-go120:
    docker:
      - image: "cimg/go:1.20"
    environment:
      runrace: true
      TIMESCALE_FACTOR: 3
 
jobs:
  "test": &test
    executor: test-go118
    steps:
      - checkout
      - run:
          name: "Build infos"
          command: go version
      - run:
          name: "Run tools tests"
          command: go run github.com/onsi/ginkgo/v2/ginkgo -race -r -v -randomize-all -trace integrationtests/tools
      - run:
          name: "Run self integration tests"
          command: go run github.com/onsi/ginkgo/v2/ginkgo -v -randomize-all -trace integrationtests/self
      - run:
          name: "Run self integration tests with race detector"
          command: go run github.com/onsi/ginkgo/v2/ginkgo -race -v -randomize-all -trace integrationtests/self
      - run:
          name: "Run self integration tests with qlog"
          command: go run github.com/onsi/ginkgo/v2/ginkgo -v -randomize-all -trace integrationtests/self -- -qlog
  go118:
    <<: *test
  go119:
    <<: *test
    executor: test-go119
  go120:
    <<: *test
    executor: test-go120

workflows:
  workflow:
    jobs:
      - go118
      - go119
      - go120
